<?php

namespace CSWeb\Cielo;

use Cielo\API30\Ecommerce\Request\CieloError;
use RuntimeException;

/**
 * IntegrationErros
 *
 * @author  Matheus Lopes Santos <fale_com_lopez@hotmail.com>
 * @version 1.0.0
 * @package Cielo
 */
class IntegrationErrors
{
    protected $errors = [
        100 => 'RequestId é obrigatório',
        101 => 'MerchantId é obrigatório',
        102 => 'Tipo de pagamento é obrigatório',
        103 => 'O tipo de pagamento deve conter apenas letras',
        104 => 'Identidade do cliente é obrigatória',
        105 => 'Nome do cliente é obrigatório',
        106 => 'ID da transação é obrigatória',
        107 => 'OrderId é inválido ou não existe',
        108 => 'Valor da transação deve ser maior que "0"',
        109 => 'A moeda de pagamento é obrigatória',
        110 => 'Moeda de pagamento inválida',
        111 => 'O país de pagamento é obrigatório',
        112 => 'O país de pagamento é inválido',
        113 => 'Código de pagamento inválido',
        114 => 'O MerchantId enviado não é um GUID',
        115 => 'O MerchantID não existe ou pertence a outro ambiente',
        116 => 'Loja bloqueada, entre em contato com o suporte Cielo',
        117 => 'Titular do cartão inválido',
        118 => 'O número do cartão é obrigatório',
        119 => 'Ao menos um tipo de pagamento deve ser enviado',
        120 => 'IP bloqueado por questões de segurança',
        121 => 'É necessário enviar os dados do cliente',
        122 => 'O campo MerchantOrderId é obrigatório',
        123 => 'Numero de parcelas deve ser superior a 1',
        124 => 'O cartão de crédito é obrigatório',
        125 => 'A data de expiração do cartão é obrigatória',
        126 => 'A data de expiração do cartão é inválida',
        127 => 'Você deve fornecer um número de cartão de crédito',
        128 => 'Numero do cartão superiro a 16 digitos',
        129 => 'Meio de pagamento não vinculado a loja ou Provider inválido',
        130 => 'Não foi possível recuperar os dados do cartão de crédito',
        131 => 'O MerchantKey é obrigatório',
        132 => 'O Merchantkey enviado não é válido',
        133 => 'Provider enviado não existe',
        134 => 'Tamanho do FingerPrint excedido',
        135 => 'Tamanho do MerchantDefinedFieldValue excedido',
        136 => 'Tamanho do ItemDataName excedido',
        137 => 'Tamanho do ItemDataSKU excedido',
        138 => 'Tamanho do PassengerDataName excedido',
        139 => 'Tamanho do PassengerDataStatus excedido',
        140 => 'Tamanho do PassengerDataEmail excedido',
        141 => 'Tamanho do PassengerDataPhone excedido',
        142 => 'Tamanho do TravelDataRoute excedido',
        143 => 'Tamanho do TravelDataJourneyType excedido',
        144 => 'Tamanho do TravelLegDataDestination excedido',
        145 => 'Tamanho do TravelLegDataOrigin excedido',
        146 => 'Tamanho do SecurityCode excedido',
        147 => 'Tamanho do endereço excedido',
        148 => 'Tamanho do número da residência excedido',
        149 => 'Tamanho do complemento excedido',
        150 => 'Tamanho do CEP excedido',
        151 => 'Tamanho do cidade excedido',
        152 => 'Tamanho do estado excedido',
        153 => 'Tamanho do país excedido',
        154 => 'Tamanho do bairro excedido',
        155 => 'Tamanho do nome do cliente excedido',
        156 => 'Tamanho da identidade do cliente excedido',
        157 => 'Tamanho do tipo de documento do cliente excedido',
        158 => 'Tamanho do email do cliente excedido',
        159 => 'Tamanho do ExtraData Name excedido',
        160 => 'Tamanho do ExtraData Value excedido',
        161 => 'Tamanho da instrução do boleto excedido',
        162 => 'Tamanho do demonstrativo do boleto excedido',
        163 => 'URL de retorno não é valida',
        166 => 'AuthorizeNow is required',
        167 => 'Antifraude não vinculado ao cadastro do lojista',
        168 => 'Recorrência não encontrada',
        169 => 'Recorrência não está ativa. Execução paralizada',
        170 => 'Cartão protegido não vinculado ao cadastro do lojista',
        171 => 'Falha no processamento do pedido - Entre em contato com o suporte Cielo',
        172 => 'Falha na validação das credenciadas enviadas',
        173 => 'Meio de pagamento não vinculado ao cadastro do lojista',
        174 => 'O número do cartão é obrigatório',
        175 => 'Código EAN é obrigatório',
        176 => 'Moeda de pagamento não suportada',
        177 => 'Número do cartão inválido',
        178 => 'Código EAD inválido',
        179 => 'O número máximo de parcelas permitidas para pagamentos recorrentes é 1',
        180 => 'Token do Cartão protegido não encontrado',
        181 => 'Token do Cartão protegido bloqueado',
        182 => 'Bandeira do cartão não enviado',
        183 => 'Data de nascimento inválida ou futura',
        184 => 'Falha no formado da requisição. Verifique o código enviado',
        185 => 'Bandeira não suportada pela API Cielo',
        186 => 'Meio de pagamento não suporta o comando enviado',
        187 => 'ExtraData Collection contém um ou mais nomes duplicados',
        188 => 'AVS com CPF inválido',
        189 => 'AVS com tamanho do endereço excedido',
        190 => 'AVS com tamanho do número excedido',
        191 => 'AVS com tamanho do bairro excedido',
        192 => 'AVS com tamanho do cep excedido',
        193 => 'O valor da divisão deve ser maior que zero',
        194 => 'Split Establishment é obrigatório',
        195 => 'PlataformId é obrigatório',
        196 => 'O endereço de entrega é obrigatório',
        197 => 'Endereço é obrigatório',
        198 => 'Número é obrigatório',
        199 => 'CEP é obrigatório',
        200 => 'Cidade é obrigatório',
        201 => 'Estado é obrigatório',
        202 => 'Bairro é obrigatório',
        203 => 'Nome do item é obrigatório',
        204 => 'Quantidade é obrigatória',
        205 => 'O tipo de item do carrinho é obrigatório',
        206 => 'Tamanho do nome do item do carrinho excedido',
        207 => 'Tamanho da descrição do item do carrinho excedido',
        208 => 'Tamanho do SKU do item do carrinho excedido',
        209 => 'Tamanho do sku do destinatário da remessa excedido',
        210 => 'Os dados de remessa não podem ser nulos',
        211 => 'O WalletKey é inválido',
        212 => 'Configuração da carteira do comerciante não encontrada',
        213 => 'O número do cartão de crédito é inválido',
        214 => 'O titular do cartão de crédito deve ter apenas letras',
        215 => 'A agência é necessária na Credencial do Boleto',
        216 => 'O endereço IP do cliente é inválido',
        300 => 'MerchantId não foi encontrado',
        301 => 'IP de solicitação não permitido',
        302 => 'MerchantOrderId enviado é duplicado',
        303 => 'OrderId enviado não existe',
        304 => 'Identidade do cliente é necessária',
        306 => 'Merchant está bloqueado',
        307 => 'Transação não encontrada',
        308 => 'Transação não disponível para captura',
        309 => 'Transação não disponível para anular',
        310 => 'O método de pagamento não suporta esta operação',
        311 => 'O reembolso não está ativado para este comerciante',
        312 => 'Transação não disponível para reembolso',
        313 => 'Pagamento recorrente não encontrado',
        314 => 'Integração inválida',
        315 => 'Não é possível alterar uma próxima recorrência com pagamento pendente',
        316 => 'Não é possível setar a próxima recorrência para uma data no passado',
        317 => 'Dia de recorrência inválido',
        318 => 'Transação não encontrada',
        319 => 'A recorrência inteligente não está ativada',
        320 => 'Não é possível atualizar a afiliação porque essa recorrência não foi salva',
        321 => 'Não é possível definir data de término como antes da próxima recorrência',
        322 => 'Zero Dollar Auth não foi habilitado',
        323 => 'Bin Query não foi habilitado',
    ];

    public function __construct(CieloError $error)
    {
        $code = $error->getCode();

        if ( array_key_exists($code, $this->errors) ) {
            throw new RuntimeException(
                $this->errors[$code]
            );
        }

        throw new RuntimeException($error->getMessage());
    }
}
